FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

WORKDIR /src

COPY . .

RUN dotnet restore ./sprints-service/Backend.Sprints.Api/Backend.Sprints.Api.csproj

RUN apk add --no-cache curl

EXPOSE 8084

WORKDIR /src/sprints-service/Backend.Sprints.Api

CMD ["dotnet", "run"]